### ISSUE TITLE
Create benchmark table if it doesn't exist

### ISSUE THREAD

**Issue by mfussenegger** [mfussenegger/cr8#74]
If someone installs cr8 via pip the benchmarks.sql file isn't included so it is rather troublesome to create the table. It should probably just be created automatically if it is missing.

And maybe provide an option to define the table name. For example the result hosts could be defined as `-r localhost:4200/<tablename>`

**Comment by mfussenegger** [comment]
@chaudum @mikethebeer what do you think about this?

**Comment by chaudum** [comment]
Think it is a good idea to create the table automatically and the `-r`.
However `<host>:<port>/<tablename>` could be a bit misleading because quite a few libraries expected in a database connection string the schema as the first part after `/`. If you don't see the `-r` argument as a connection string, it is totally fine though.

**Comment by mfussenegger** [comment]
Would `<host>:<port>/?table=<tablename>` make more sense then? It is kind of a connectionstring. Want to be able to have a `psql://` scheme later on.
