### ISSUE TITLE
insert-fake-data number of records

### ISSUE THREAD

**Issue by fjblau** [mfussenegger/cr8#89]
It seems to insert 1000 records, regardless of the value passed to num-records.

**Comment by mfussenegger** [comment]
Are you by any change trying to insert less than 1000?
There was this issue that it didn't work as long as the bulk_size is greater then the number of records to insert.
You can work around that by setting the bulk-size to the same number as the number of records to insert.

This is fixed in master (https://github.com/mfussenegger/cr8/commit/00e7b35708c3660a9826b4d501f625b4e605a8c2)

**Comment by fjblau** [comment]
OK, that makes more sense... I'll give that a try.

**Comment by mfussenegger** [comment]
I assume this worked? If not please re-open
